ColumnNames = {
    "ga:yearMonth": "YearMonth",
    "ga:users": "Users",
    "ga:newUsers": "New Users",
    "ga:sessions": "Sessions",
    "ga:bounceRate": "Bounce Rate",
    "ga:pageviewsPerSession": "Pages / Session",
    "ga:avgSessionDuration": "Avg. Session Duration Bucket",
    "ga:transactions": "Transactions",
    "ga:transactionRevenue": "Revenue",
    "ga:transactionsPerSession": "Ecommerce Converstion Rate",
    "ga:revenuePerTransaction": "Avg. Order Value",
    "ga:pageviews": "Pageviews",
    "ga:uniquePageviews": "Unique Pageviews",
    "ga:timeOnPage": "Time on Page",
    "ga:entrances": "Entrances",
    "ga:exits": "Exits",
    "ga:pageValue": "Page Value",
    "ga:totalEvents": "Total Events",
    "ga:uniqueEvents": "Unique Events",
    "ga:eventValue": "Event Value",
    "ga:avgEventValue": "Avg. Value",
    "ga:goalCompletionsAll": "Goal Completions",
    "ga:goalValueAll": "Goal Value",
    "ga:itemRevenue": "Product Revenue",
    "ga:uniquePurchases": "Unique Purchases",
    "ga:itemQuantity": "Quantity",
    "ga:revenuePerItem": "Avg. Price",
    "ga:itemsPerPurchase": "Avg. QTY",
    "ga:productRefunds": "Product Refunds",
    "ga:transactionTax": "Tax",
    "ga:transactionShipping": "Shipping",
    "ga:refundAmount": "Refund Amount",
    "ga:language": "Language",
    "ga:userType": "User Type",
    "ga:sessionCount": "Count of Sessions",
    "ga:daysSinceLastSession": "Days Since Last Session",
    "ga:sessionDurationBucket": "Session Duration Bucket",
    "ga:pageDepth": "Page Depth",
    "ga:browser": "Browser",
    "ga:operatingSystem": "Operating System",
    "ga:networkLocation": "Network",
    "ga:hostname": "Hostname",
    "ga:mobileDeviceInfo": "Mobile Device Info",
    "ga:continent": "Continent",
    "ga:subContinent": "Sub-Continent",
    "ga:country": "Country",
    "ga:city": "City",
    "ga:source": "Source",
    "ga:medium": "Medium",
    "ga:channelGrouping": "Default Channel Grouping",
    "ga:campaign": "Campaign",
    "ga:pagePath": "Page",
    "ga:pageTitle": "Page Title",
    "ga:landingPagePath": "Landing Page",
    "ga:exitPagePath": "Exit Page",
    "ga:eventCategory": "Event Category",
    "ga:eventAction": "Event Action",
    "ga:eventLabel": "Event Label",
    "ga:goalCompletionLocation": "Goal Completion Location",
    "ga:productName": "Product",
    "ga:productBrand": "Product Brand",
    "ga:productSku": "Product SKU",
    "ga:transactionId": "Transaction ID",
}
